# Generated by Django 5.2.5 on 2025-09-22 01:01

import cloudinary_storage.storage
import cloudinary_storage.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='intro_video',
            field=models.FileField(blank=True, help_text='Upload an intro video (optional)', null=True, storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='user_videos/', validators=[cloudinary_storage.validators.validate_video]),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='Upload a profile image (optional)', null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='user_profiles/'),
        ),
    ]
