# Generated by Django 5.2.5 on 2025-10-03 21:02

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PublicAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('image', cloudinary.models.CloudinaryField(blank=True, help_text='Upload an image for the announcement (optional, recommended for events)', max_length=255, null=True)),
                ('event_date', models.DateField(help_text='Date of the event (e.g., graduation)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Public Announcement',
                'verbose_name_plural': 'Public Announcements',
                'ordering': ['-event_date', '-created_at'],
            },
        ),
    ]
