# Generated by Django 5.2.5 on 2025-10-03 21:18

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_announcements', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publicannouncement',
            options={'ordering': ['-event_date', '-created_at']},
        ),
        migrations.AlterField(
            model_name='publicannouncement',
            name='event_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='publicannouncement',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
