# Generated by Django 5.2.5 on 2025-09-22 01:01

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_remove_material_course_material_video_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='video_url',
        ),
        migrations.AddField(
            model_name='material',
            name='video',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Upload video directly to Cloudinary', max_length=255, null=True),
        ),
    ]
