# Generated by Django 5.2.5 on 2025-09-22 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_material_video_url_material_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='video_url',
            field=models.URLField(blank=True, help_text='Optional: paste YouTube video link', null=True),
        ),
    ]
