# Generated by Django 5.2.5 on 2025-10-11 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='course',
        ),
    ]
