# Generated by Django 5.2.5 on 2025-09-24 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editprofile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='level',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='program',
        ),
    ]
