# Generated by Django 5.2.5 on 2025-09-24 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editprofile', '0002_remove_userprofile_level_remove_userprofile_program'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='specialization',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='title',
        ),
    ]
