# Generated by Django 5.2.5 on 2025-09-24 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editprofile', '0003_remove_userprofile_avatar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
