# Generated by Django 5.2.5 on 2025-09-24 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editprofile', '0004_remove_userprofile_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('LECTURER', 'Lecturer'), ('STUDENT', 'Student')], default='STUDENT', max_length=20),
        ),
    ]
