# Generated by Django 5.2.5 on 2025-09-24 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editprofile', '0005_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
