# Generated by Django 5.2.5 on 2025-10-08 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editprofile', '0007_alter_userprofile_id_alter_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('LECTURER', 'Lecturer'), ('STUDENT', 'Student')], default='STUDENT', max_length=20),
        ),
    ]
